# Validation prompts are primarily from a public github repo, [Sana](https://github.com/NVlabs/Sana).
# You can find those prompts here (https://github.com/NVlabs/Sana/blob/main/configs/sana_base.yaml#L120-L125
val_prompts:
  - A capybara holding a sign that reads "Hello World"
  - A portrait photo of a girl, photograph, highly detailed face, depth of field
  - Self-portrait oil painting, a beautiful cyborg with golden hair, 8k
  - Astronaut in a jungle, cold color palette, muted colors, detailed, 8k
  - A photo of beautiful mountain with realistic sunset and blue lake, highly detailed, masterpiece
